import os

from dotenv import load_dotenv

load_dotenv()

PINECONE_API_KEY = os.getenv("PINECONE_API_KEY")
CONTENTFUL_ACCESS_TOKEN = os.getenv("CONTENTFUL_ACCESS_TOKEN")
CONTENTFUL_SPACE_ID = os.getenv("CONTENTFUL_SPACE_ID")

assert PINECONE_API_KEY, "PINECONE_API_KEY not set in .env"
assert CONTENTFUL_ACCESS_TOKEN, "CONTENTFUL_ACCESS_TOKEN not set in .env"
assert CONTENTFUL_SPACE_ID, "CONTENTFUL_SPACE_ID not set in .env"

# Pinecone settings
PINECONE_INDEX_NAME = "platform-v2"
PINECONE_NAMESPACE = "search"

# Dense embedding model (Pinecone-hosted multilingual-e5-large)
DENSE_MODEL = "multilingual-e5-large"
DENSE_DIM = 1024

# BM25 corpus statistics file (generated by setup_bm25.py)
BM25_STATS_PATH = "data/bm25_corpus_stats.json"
